export * from "./Gallery/Gallery";
export * from "./CompareSection/CompareSection";
export * from "./Header/Header";
export * from "./Footer/Footer";
export * from "./Consulting/Consulting";
export * from "./Projects/Projects";
export * from "./Curtains/Curtains";
export * from "./Testimonials/Testimonials";
export * from "./Presentation/Presentation";
